import { api, API_BASE_URL, toQuery } from './apiClient';
import { repository } from '@/data/repository';
import type {
  AdminOrderQuery,
  Order,
  OrderList,
  OrderListMeta,
  PlaceOrderInput,
} from '@/types';

/**
 * Orders — the only module that talks to the order endpoints.
 *
 * Same contract style as every other service: components and hooks call these
 * functions and never touch `fetch`. Money is deliberately absent from every
 * request shape — the server prices orders from its own data, so there is
 * nothing here for a client to tamper with.
 */

/**
 * The API returns `{ data, meta }` for list endpoints, so these go through
 * `api.raw` to keep the pagination metadata that `api.get` would discard.
 */
async function fetchList(path: string): Promise<OrderList> {
  const body = await api.raw<Order[]>(path);
  const orders = body.data ?? [];
  const meta: OrderListMeta = body.meta ?? {
    total: orders.length,
    page: 1,
    pageSize: orders.length,
    pageCount: 1,
  };
  return { orders, meta };
}

export const orderService = {
  /* ─────────────── Customer ─────────────── */

  /**
   * Places the order.
   *
   * `idempotencyKey` is generated by the caller (the checkout page) once per
   * attempt, so a double-clicked button reuses the same key and the server
   * returns the original order instead of creating a duplicate.
   */
  async place(input: PlaceOrderInput): Promise<Order> {
    const order = await api.post<Order>('/orders', input);
    // Stock changed, so any cached product view is now stale.
    repository.invalidate();
    return order;
  },

  /** The signed-in customer's own orders. */
  async listMine(page = 1, pageSize = 20): Promise<OrderList> {
    return fetchList(`/orders${toQuery({ page, pageSize })}`);
  },

  /** One of the signed-in customer's orders, by id or order number. */
  async getMine(idOrNumber: string): Promise<Order> {
    return api.get<Order>(`/orders/${encodeURIComponent(idOrNumber)}`);
  },

  /**
   * The shipping fee the server will actually charge for this subtotal.
   * Asking the backend keeps the displayed fee and the charged fee in sync.
   */
  async shippingQuote(
    subtotal: number,
    items?: { productId: string; quantity: number }[],
  ): Promise<{ shippingFee: number; freeShippingThreshold: number }> {
    const query: Record<string, string | number> = { subtotal };
    if (items && items.length > 0) {
      query.items = JSON.stringify(items);
    }
    return api.get<{ shippingFee: number; freeShippingThreshold: number }>(
      `/orders/shipping-quote${toQuery(query)}`,
    );
  },

  /**
   * Absolute URL for the PDF invoice.
   *
   * A plain link (not fetch) so the browser handles the download natively on
   * both desktop and mobile; the session cookie rides along automatically.
   */
  invoiceUrl(idOrNumber: string): string {
    return `${API_BASE_URL}/orders/${encodeURIComponent(idOrNumber)}/invoice`;
  },

  /* ─────────────── Admin ─────────────── */

  async listAll(query: AdminOrderQuery = {}): Promise<OrderList> {
    return fetchList(
      `/admin/orders${toQuery({
        search: query.search || undefined,
        status: query.status || undefined,
        sort: query.sort,
        page: query.page,
        pageSize: query.pageSize,
      })}`,
    );
  },

  async getAny(idOrNumber: string): Promise<Order> {
    return api.get<Order>(`/admin/orders/${encodeURIComponent(idOrNumber)}`);
  },

  /** Admin-only. The server rejects nonsensical transitions with 409. */
  async updateStatus(id: string, status: Order['status']): Promise<Order> {
    const order = await api.patch<Order>(`/admin/orders/${encodeURIComponent(id)}/status`, { status });
    // Cancelling restores stock, so product data may have changed.
    repository.invalidate();
    return order;
  },

  /** Admin-only: Permanently delete an order and its line items. */
  async delete(idOrNumber: string): Promise<{ id: string; orderNumber: string }> {
    return api.delete<{ id: string; orderNumber: string }>(
      `/admin/orders/${encodeURIComponent(idOrNumber)}`,
    );
  },

  /** Admin-only: Bulk delete multiple selected orders safely. */
  async bulkDelete(ids: string[]): Promise<{ count: number; deletedIds: string[] }> {
    return api.post<{ count: number; deletedIds: string[] }>('/admin/orders/bulk-delete', { ids });
  },
};

